//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersUnderProject
    {
        public int AssignedID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ProjectID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
